package com.demo.jfinal.model;

import com.demo.jfinal.model.base.BaseUser;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();

	public static void main(String[] args) {
		List<User> users = User.dao.find("select * from user");
		System.out.println(users);
	}
}
