package com.demo.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAddress<M extends BaseAddress<M>> extends Model<M> implements IBean {

	/**
	 * 收货地址表主键id
	 */
	public M setAddressId(java.lang.String addressId) {
		set("address_id", addressId);
		return (M)this;
	}
	
	/**
	 * 收货地址表主键id
	 */
	public java.lang.String getAddressId() {
		return getStr("address_id");
	}

	/**
	 * 用户主键ID
	 */
	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户主键ID
	 */
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	/**
	 * 收货人姓名
	 */
	public M setAddressName(java.lang.String addressName) {
		set("address_name", addressName);
		return (M)this;
	}
	
	/**
	 * 收货人姓名
	 */
	public java.lang.String getAddressName() {
		return getStr("address_name");
	}

	/**
	 * 联系方式
	 */
	public M setAddressPhone(java.lang.String addressPhone) {
		set("address_phone", addressPhone);
		return (M)this;
	}
	
	/**
	 * 联系方式
	 */
	public java.lang.String getAddressPhone() {
		return getStr("address_phone");
	}

	/**
	 * 所在地区
	 */
	public M setAddressRegion(java.lang.String addressRegion) {
		set("address_region", addressRegion);
		return (M)this;
	}
	
	/**
	 * 所在地区
	 */
	public java.lang.String getAddressRegion() {
		return getStr("address_region");
	}

	/**
	 * 详细收货地址
	 */
	public M setAddressLocation(java.lang.String addressLocation) {
		set("address_location", addressLocation);
		return (M)this;
	}
	
	/**
	 * 详细收货地址
	 */
	public java.lang.String getAddressLocation() {
		return getStr("address_location");
	}

	/**
	 * 是否设置为默认地址(0普通状态,1是默认)
	 */
	public M setAddressState(java.lang.Integer addressState) {
		set("address_state", addressState);
		return (M)this;
	}
	
	/**
	 * 是否设置为默认地址(0普通状态,1是默认)
	 */
	public java.lang.Integer getAddressState() {
		return getInt("address_state");
	}

	/**
	 * 时间
	 */
	public M setAddressTime(java.util.Date addressTime) {
		set("address_time", addressTime);
		return (M)this;
	}
	
	/**
	 * 时间
	 */
	public java.util.Date getAddressTime() {
		return get("address_time");
	}

}
